// Template Engine for Question Generation
const TemplateEngine = (function() {
    const history = {};

    function getNums(q) {
        return q.match(/-?\d+(\.\d+)?/g) || [];
    }

    const templates = {
        'Addition': [
            (nums) => `${nums[0]} + ${nums[1]} = ?`,
            (nums) => `What is the sum of ${nums[0]} and ${nums[1]}?`,
            (nums) => `Add ${nums[0]} and ${nums[1]}.`,
            (nums) => `If you have ${nums[0]} apples and get ${nums[1]} more, how many do you have?`,
            (nums) => `${nums[0]} increased by ${nums[1]} is?`,
            (nums) => `Calculate: ${nums[0]} + ${nums[1]}.`,
            (nums) => `Find the total of ${nums[0]} and ${nums[1]}.`,
            (nums) => `${nums[1]} more than ${nums[0]} is?`,
            (nums) => `Together, ${nums[0]} and ${nums[1]} make?`,
            (nums) => `What is ${nums[0]} plus ${nums[1]}?`,
            (nums) => `A store sold ${nums[0]} items and then ${nums[1]} items. Total sold?`,
            (nums) => `If a train travels ${nums[0]} km and then ${nums[1]} km, total distance?`,
            (nums) => `Sum of ${nums[0]} and ${nums[1]} equals:`,
            (nums) => `Combine ${nums[0]} and ${nums[1]}.`,
            (nums) => `Evaluate ${nums[0]} + ${nums[1]}.`,
        ],
        'Subtraction': [
            (nums) => `${nums[0]} - ${nums[1]} = ?`,
            (nums) => `What is ${nums[0]} minus ${nums[1]}?`,
            (nums) => `Subtract ${nums[1]} from ${nums[0]}.`,
            (nums) => `${nums[0]} decreased by ${nums[1]} is?`,
            (nums) => `If you have ${nums[0]} coins and spend ${nums[1]}, how many are left?`,
            (nums) => `Difference between ${nums[0]} and ${nums[1]}?`,
            (nums) => `Take away ${nums[1]} from ${nums[0]}.`,
            (nums) => `Calculate: ${nums[0]} - ${nums[1]}.`,
            (nums) => `${nums[1]} less than ${nums[0]} is?`,
            (nums) => `How much is left if you remove ${nums[1]} from ${nums[0]}?`,
            (nums) => `A tank had ${nums[0]} liters, ${nums[1]} leaked. Remaining?`,
            (nums) => `Evaluate ${nums[0]} - ${nums[1]}.`,
            (nums) => `What is the result of ${nums[0]} - ${nums[1]}?`,
            (nums) => `Find ${nums[0]} minus ${nums[1]}.`,
            (nums) => `${nums[0]} subtract ${nums[1]}.`,
        ],
        'Multiplication': [
            (nums) => `${nums[0]} * ${nums[1]} = ?`,
            (nums) => `Multiply ${nums[0]} by ${nums[1]}.`,
            (nums) => `What is the product of ${nums[0]} and ${nums[1]}?`,
            (nums) => `Calculate: ${nums[0]} * ${nums[1]}.`,
            (nums) => `Find the product of ${nums[0]} and ${nums[1]}.`,
            (nums) => `If one box has ${nums[0]} items, how many in ${nums[1]} boxes?`,
            (nums) => `${nums[0]} times ${nums[1]} is?`,
            (nums) => `What is ${nums[0]} multiplied by ${nums[1]}?`,
            (nums) => `Evaluate ${nums[0]} * ${nums[1]}.`,
            (nums) => `Product of ${nums[0]} and ${nums[1]} equals:`,
            (nums) => `A rectangular field is ${nums[0]}m by ${nums[1]}m. Area?`,
            (nums) => `If you save ${nums[0]} dollars for ${nums[1]} days, total?`,
            (nums) => `${nums[1]} groups of ${nums[0]} is?`,
            (nums) => `Compute ${nums[0]} * ${nums[1]}.`,
            (nums) => `Find ${nums[0]} * ${nums[1]}.`,
        ],
        'Division': [
            (nums) => `${nums[0]} / ${nums[1]} = ?`,
            (nums) => `Divide ${nums[0]} by ${nums[1]}.`,
            (nums) => `What is the quotient of ${nums[0]} and ${nums[1]}?`,
            (nums) => `Calculate: ${nums[0]} / ${nums[1]}.`,
            (nums) => `Find the result of ${nums[0]} / ${nums[1]}.`,
            (nums) => `If ${nums[0]} items are shared among ${nums[1]} people, each gets?`,
            (nums) => `${nums[0]} divided by ${nums[1]} is?`,
            (nums) => `What is ${nums[0]} over ${nums[1]}?`,
            (nums) => `Evaluate ${nums[0]} / ${nums[1]}.`,
            (nums) => `Quotient of ${nums[0]} and ${nums[1]} equals:`,
            (nums) => `A ${nums[0]}m rope is cut into ${nums[1]} equal pieces. Length?`,
            (nums) => `Distribute ${nums[0]} into ${nums[1]} equal groups.`,
            (nums) => `How many times does ${nums[1]} go into ${nums[0]}?`,
            (nums) => `Compute ${nums[0]} / ${nums[1]}.`,
            (nums) => `Find ${nums[0]} / ${nums[1]}.`,
        ],
        'Squares': [
            (nums) => `What is ${nums[0]}^2?`,
            (nums) => `Square ${nums[0]}.`,
            (nums) => `Calculate ${nums[0]} squared.`,
            (nums) => `Find ${nums[0]} to the power of 2.`,
            (nums) => `What is the area of a square with side ${nums[0]}?`,
            (nums) => `Evaluate ${nums[0]}^2.`,
            (nums) => `Compute ${nums[0]} * ${nums[0]}.`,
            (nums) => `What is the square of ${nums[0]}?`,
            (nums) => `Find the value of ${nums[0]} squared.`,
            (nums) => `${nums[0]} squared is?`,
            (nums) => `Multiply ${nums[0]} by itself.`,
            (nums) => `What is ${nums[0]} times ${nums[0]}?`,
            (nums) => `The square of ${nums[0]} equals:`,
            (nums) => `Determine ${nums[0]} squared.`,
            (nums) => `Solve: ${nums[0]}^2.`,
        ],
        'Cube Roots': [
            (nums) => `Cube root of ${nums[0]} = ?`,
            (nums) => `Find the cube root of ${nums[0]}.`,
            (nums) => `What number cubed is ${nums[0]}?`,
            (nums) => `Calculate the cube root of ${nums[0]}.`,
            (nums) => `What is ${nums[0]}^(1/3)?`,
            (nums) => `Evaluate cube root of ${nums[0]}.`,
            (nums) => `Determine the cube root of ${nums[0]}.`,
            (nums) => `If a cube has volume ${nums[0]}, what is its side?`,
            (nums) => `Find x if x^3 = ${nums[0]}.`,
            (nums) => `What is the principal cube root of ${nums[0]}?`,
            (nums) => `The cube root of ${nums[0]} equals:`,
            (nums) => `Compute cube root of ${nums[0]}.`,
            (nums) => `Solve for the cube root of ${nums[0]}.`,
            (nums) => `Which number multiplied by itself three times gives ${nums[0]}?`,
            (nums) => `Find the 3rd root of ${nums[0]}.`,
        ],
        'Percentage': [
            (nums) => `What is ${nums[0]}% of ${nums[1]}?`,
            (nums) => `Calculate ${nums[0]}% of ${nums[1]}.`,
            (nums) => `Find ${nums[0]} percent of ${nums[1]}.`,
            (nums) => `If you have ${nums[1]} and take ${nums[0]}%, how much do you have?`,
            (nums) => `${nums[0]}% of ${nums[1]} equals:`,
            (nums) => `Evaluate ${nums[0]}% of ${nums[1]}.`,
            (nums) => `Determine ${nums[0]}% of ${nums[1]}.`,
            (nums) => `A shirt costs ${nums[1]} and is discounted by ${nums[0]}%. What is the discount?`,
            (nums) => `What amount is ${nums[0]}% of ${nums[1]}?`,
            (nums) => `Find the value of ${nums[0]}% of ${nums[1]}.`,
            (nums) => `Compute ${nums[0]}% of ${nums[1]}.`,
            (nums) => `Solve: ${nums[0]}% of ${nums[1]}.`,
            (nums) => `If the total is ${nums[1]}, what is ${nums[0]}%?`,
            (nums) => `${nums[0]} percent of ${nums[1]} is?`,
            (nums) => `What is the percentage value of ${nums[0]}% from ${nums[1]}?`,
        ],
        'Profit & Loss': [
            (nums) => `An item costs ${nums[0]} and is sold at a ${nums[1]}% profit. What is the profit?`,
            (nums) => `Find the profit if cost price is ${nums[0]} and profit is ${nums[1]}%.`,
            (nums) => `Calculate profit for CP=${nums[0]} with a margin of ${nums[1]}%.`,
            (nums) => `If a merchant buys for ${nums[0]} and gains ${nums[1]}%, what is the gain?`,
            (nums) => `Determine the profit on ${nums[0]} at ${nums[1]}%.`,
            (nums) => `What is the profit amount for ${nums[0]} at ${nums[1]}%?`,
            (nums) => `Evaluate profit: CP = ${nums[0]}, Profit% = ${nums[1]}%.`,
            (nums) => `A car bought for ${nums[0]} is sold for ${nums[1]}% profit. Profit made?`,
            (nums) => `Find the gain if an item costing ${nums[0]} is sold at ${nums[1]}% gain.`,
            (nums) => `Profit earned on ${nums[0]} at ${nums[1]}% is?`,
            (nums) => `Calculate the absolute profit given CP=${nums[0]} and rate=${nums[1]}%.`,
            (nums) => `If cost is ${nums[0]}, what is a ${nums[1]}% profit?`,
            (nums) => `Gain on an investment of ${nums[0]} at ${nums[1]}% is?`,
            (nums) => `Solve for profit: CP=${nums[0]}, Rate=${nums[1]}%.`,
            (nums) => `How much profit is made on ${nums[0]} at ${nums[1]}%?`,
        ],
        'Simple Interest': [
            (nums) => `Find the simple interest on ${nums[0]} at ${nums[1]}% per year for ${nums[2]} years.`,
            (nums) => `Calculate SI for P=${nums[0]}, R=${nums[1]}%, T=${nums[2]}.`,
            (nums) => `What is the simple interest if ${nums[0]} is invested at ${nums[1]}% for ${nums[2]} years?`,
            (nums) => `Determine the interest earned on ${nums[0]} over ${nums[2]} years at ${nums[1]}%.`,
            (nums) => `Evaluate SI: Principal=${nums[0]}, Rate=${nums[1]}%, Time=${nums[2]}.`,
            (nums) => `If you borrow ${nums[0]} at ${nums[1]}% SI for ${nums[2]} years, what is the interest?`,
            (nums) => `Find the total interest on a ${nums[0]} loan at ${nums[1]}% for ${nums[2]} years.`,
            (nums) => `Compute simple interest for ${nums[0]} at ${nums[1]}% p.a. for ${nums[2]} yrs.`,
            (nums) => `What interest accrues on ${nums[0]} at ${nums[1]}% simple interest in ${nums[2]} years?`,
            (nums) => `Calculate the SI generated by ${nums[0]} at ${nums[1]}% over ${nums[2]} years.`,
            (nums) => `The simple interest on ${nums[0]} at ${nums[1]}% for ${nums[2]} years is:`,
            (nums) => `Find SI: ${nums[0]} principal, ${nums[1]}% rate, ${nums[2]} time.`,
            (nums) => `How much interest is earned on ${nums[0]} at ${nums[1]}% for ${nums[2]} years?`,
            (nums) => `Solve for simple interest given P=${nums[0]}, R=${nums[1]}%, T=${nums[2]}.`,
            (nums) => `What is the interest on ${nums[0]} (Rate: ${nums[1]}%, Time: ${nums[2]} years)?`,
        ],
        'Compound Interest': [
            (nums) => `Find the compound interest on ${nums[0]} at ${nums[1]}% per year for ${nums[2]} years.`,
            (nums) => `Calculate CI for P=${nums[0]}, R=${nums[1]}%, T=${nums[2]}.`,
            (nums) => `What is the compound interest if ${nums[0]} is invested at ${nums[1]}% for ${nums[2]} years?`,
            (nums) => `Determine the CI earned on ${nums[0]} over ${nums[2]} years at ${nums[1]}%.`,
            (nums) => `Evaluate CI: Principal=${nums[0]}, Rate=${nums[1]}%, Time=${nums[2]}.`,
            (nums) => `If you borrow ${nums[0]} at ${nums[1]}% CI for ${nums[2]} years, what is the interest?`,
            (nums) => `Find the total compound interest on a ${nums[0]} loan at ${nums[1]}% for ${nums[2]} years.`,
            (nums) => `Compute compound interest for ${nums[0]} at ${nums[1]}% p.a. for ${nums[2]} yrs.`,
            (nums) => `What compound interest accrues on ${nums[0]} at ${nums[1]}% in ${nums[2]} years?`,
            (nums) => `Calculate the CI generated by ${nums[0]} at ${nums[1]}% over ${nums[2]} years.`,
            (nums) => `The compound interest on ${nums[0]} at ${nums[1]}% for ${nums[2]} years is:`,
            (nums) => `Find CI: ${nums[0]} principal, ${nums[1]}% rate, ${nums[2]} time.`,
            (nums) => `How much compound interest is earned on ${nums[0]} at ${nums[1]}% for ${nums[2]} years?`,
            (nums) => `Solve for compound interest given P=${nums[0]}, R=${nums[1]}%, T=${nums[2]}.`,
            (nums) => `What is the CI on ${nums[0]} (Rate: ${nums[1]}%, Time: ${nums[2]} years)?`,
        ],
        'Ratio & Proportion': [
            (nums) => `If A:B = ${nums[0]}:${nums[1]} and A = ${nums[2]}, what is B?`,
            (nums) => `Two numbers are in ratio ${nums[0]}:${nums[1]}. If the first is ${nums[2]}, find the second.`,
            (nums) => `A and B share money in ratio ${nums[0]}:${nums[1]}. If A gets ${nums[2]}, what does B get?`,
            (nums) => `For ratio ${nums[0]}:${nums[1]}, if the antecedent is ${nums[2]}, find the consequent.`,
            (nums) => `Solve for x: ${nums[0]}:${nums[1]} :: ${nums[2]}:x`,
            (nums) => `If the ratio of boys to girls is ${nums[0]}:${nums[1]} and there are ${nums[2]} boys, how many girls?`,
            (nums) => `Calculate B if A:B = ${nums[0]}:${nums[1]} and A=${nums[2]}.`,
            (nums) => `Determine the missing value in proportion ${nums[0]}/${nums[1]} = ${nums[2]}/x.`,
            (nums) => `Find the second term if ratio is ${nums[0]}:${nums[1]} and first term is ${nums[2]}.`,
            (nums) => `In a mixture, parts are ${nums[0]}:${nums[1]}. If part 1 is ${nums[2]}, what is part 2?`,
            (nums) => `If A/B = ${nums[0]}/${nums[1]} and A = ${nums[2]}, find B.`,
            (nums) => `Compute the proportional value B given A:B = ${nums[0]}:${nums[1]} and A=${nums[2]}.`,
            (nums) => `What is the value of B if A is ${nums[2]} in ratio ${nums[0]}:${nums[1]}?`,
            (nums) => `Given proportion ${nums[0]}:${nums[1]} = ${nums[2]}:B, what is B?`,
            (nums) => `Evaluate B when A=${nums[2]} and A:B=${nums[0]}:${nums[1]}.`,
        ],
        'Average': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Average)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Average)?`,
        ],
        'Time & Work': [
            (nums) => `A and B can each finish a job in ${nums[0]} days. How many days will they take together?`,
            (nums) => `If two workers both take ${nums[0]} days to paint a house, time taken working together?`,
            (nums) => `Worker 1 takes ${nums[0]} days, Worker 2 takes ${nums[0]} days. Total time together?`,
            (nums) => `Calculate the combined work time if each takes ${nums[0]} days.`,
            (nums) => `Find the joint completion time for a task taking ${nums[0]} days individually.`,
            (nums) => `How long to finish a project if A takes ${nums[0]} days and B takes ${nums[0]} days?`,
            (nums) => `Evaluate time together if individual times are both ${nums[0]} days.`,
            (nums) => `If it takes you ${nums[0]} hrs and me ${nums[0]} hrs, how long if we share?`,
            (nums) => `Combined efficiency of two identical workers taking ${nums[0]} days each?`,
            (nums) => `Time to complete if A = ${nums[0]}d and B = ${nums[0]}d.`,
            (nums) => `Together time for two agents working at ${nums[0]} days per task.`,
            (nums) => `Find the parallel work time given individual time ${nums[0]}.`,
            (nums) => `Solve: Worker A (${nums[0]}d) + Worker B (${nums[0]}d) = ?`,
            (nums) => `Determine the team duration if members take ${nums[0]} days individually.`,
            (nums) => `What is the joint rate of completion for individual ${nums[0]} days?`,
        ],
        'Time Speed Distance': [
            (nums) => `A vehicle travels at ${nums[0]} km/h for ${nums[1]} hours. What distance does it cover?`,
            (nums) => `Find distance if speed is ${nums[0]} km/h and time is ${nums[1]} hours.`,
            (nums) => `Calculate total distance covered at ${nums[0]} km/h over ${nums[1]} hrs.`,
            (nums) => `If a train moves at ${nums[0]} km/h, how far does it go in ${nums[1]} hours?`,
            (nums) => `Determine distance D for S=${nums[0]} and T=${nums[1]}.`,
            (nums) => `Evaluate the distance given speed=${nums[0]} and time=${nums[1]}.`,
            (nums) => `What is the distance travelled in ${nums[1]} hours at ${nums[0]} speed?`,
            (nums) => `Distance = ? if S=${nums[0]}, T=${nums[1]}.`,
            (nums) => `Compute distance for a journey of ${nums[1]} hours at ${nums[0]} km/h.`,
            (nums) => `Find the length of a trip taking ${nums[1]} hours at ${nums[0]} km/h.`,
            (nums) => `How far do you travel at ${nums[0]} km/h in ${nums[1]} hours?`,
            (nums) => `Calculate D = S * T for S=${nums[0]}, T=${nums[1]}.`,
            (nums) => `Solve for distance: Speed ${nums[0]}, Time ${nums[1]}.`,
            (nums) => `A cars speed is ${nums[0]} km/h. Distance in ${nums[1]} hours?`,
            (nums) => `Given v=${nums[0]} and t=${nums[1]}, find d.`,
        ],
        'Boats & Streams': [
            (nums) => `A boat moves at ${nums[0]} km/h in still water and the stream is ${nums[1]} km/h. What is its downstream speed?`,
            (nums) => `Calculate downstream speed: boat ${nums[0]} km/h, stream ${nums[1]} km/h.`,
            (nums) => `Find the effective speed of a boat (${nums[0]} km/h) going with a ${nums[1]} km/h current.`,
            (nums) => `What is the speed downstream if still water speed is ${nums[0]} and current is ${nums[1]}?`,
            (nums) => `Evaluate downstream velocity for boat=${nums[0]}, river=${nums[1]}.`,
            (nums) => `Determine the boat speed with the flow: boat=${nums[0]}, flow=${nums[1]}.`,
            (nums) => `If a swimmer speed is ${nums[0]} and river is ${nums[1]}, speed downstream?`,
            (nums) => `Compute downstream speed given B=${nums[0]} and S=${nums[1]}.`,
            (nums) => `Find the total speed going downstream (Boat: ${nums[0]}, Stream: ${nums[1]}).`,
            (nums) => `Speed of boat with current? B=${nums[0]}, C=${nums[1]}.`,
            (nums) => `Calculate the downstream rate: boat=${nums[0]}, water=${nums[1]}.`,
            (nums) => `What is the combined speed of boat (${nums[0]}) and stream (${nums[1]})?`,
            (nums) => `Solve for downstream speed: v_b=${nums[0]}, v_s=${nums[1]}.`,
            (nums) => `A ship goes ${nums[0]} in still water. With a ${nums[1]} current, speed is?`,
            (nums) => `Find downstream rate given boat speed ${nums[0]} and stream ${nums[1]}.`,
        ],
        'Pipes & Cisterns': [
            (nums) => `Two identical pipes each fill a tank in ${nums[0]} hours. How long do they take together?`,
            (nums) => `If pipe A takes ${nums[0]}h and pipe B takes ${nums[0]}h, time together?`,
            (nums) => `Calculate the time to fill a tank using two pipes of ${nums[0]}h capacity.`,
            (nums) => `Find the combined filling time for two identical ${nums[0]} hour pipes.`,
            (nums) => `Determine the joint fill rate if both pipes take ${nums[0]} hours individually.`,
            (nums) => `How many hours to fill if both pipes take ${nums[0]} hours alone?`,
            (nums) => `Evaluate the combined time for two ${nums[0]}h pipes.`,
            (nums) => `If two taps fill a cistern in ${nums[0]} hrs each, combined time?`,
            (nums) => `Compute the total fill time using two ${nums[0]}h taps.`,
            (nums) => `Time to fill cistern if tap 1 = ${nums[0]}h and tap 2 = ${nums[0]}h.`,
            (nums) => `Find parallel fill time given individual time ${nums[0]}h.`,
            (nums) => `Solve: Tap A (${nums[0]}h) + Tap B (${nums[0]}h) = ?`,
            (nums) => `What is the joint completion time for ${nums[0]}h pipes?`,
            (nums) => `Calculate the team duration if members take ${nums[0]} hours individually.`,
            (nums) => `Together time for two identical pipes working at ${nums[0]} hours per task.`,
        ],
        'Mensuration': [
            (nums) => `Find the area of a rectangle with length ${nums[0]} cm and width ${nums[1]} cm.`,
            (nums) => `Calculate the area of a rectangle of ${nums[0]} by ${nums[1]}.`,
            (nums) => `What is the surface area of a ${nums[0]}m x ${nums[1]}m rectangular floor?`,
            (nums) => `Determine the area given length=${nums[0]} and width=${nums[1]}.`,
            (nums) => `Evaluate the area of a rectangle with sides ${nums[0]} and ${nums[1]}.`,
            (nums) => `If a field is ${nums[0]}m long and ${nums[1]}m wide, what is its area?`,
            (nums) => `Compute the rectangle area for L=${nums[0]}, W=${nums[1]}.`,
            (nums) => `Find the area of a ${nums[0]}x${nums[1]} rectangle.`,
            (nums) => `Area = ? if length is ${nums[0]} and breadth is ${nums[1]}.`,
            (nums) => `Calculate L * W for ${nums[0]} and ${nums[1]}.`,
            (nums) => `What is the enclosed area for dimensions ${nums[0]} and ${nums[1]}?`,
            (nums) => `Solve for area: length ${nums[0]}, width ${nums[1]}.`,
            (nums) => `Find the square footage of a ${nums[0]} by ${nums[1]} room.`,
            (nums) => `Determine area of a quadrilateral with sides ${nums[0]} and ${nums[1]}.`,
            (nums) => `Evaluate area given l=${nums[0]} and w=${nums[1]}.`,
        ],
        'Geometry': [
            (nums) => `Two angles of a triangle are ${nums[0]} degrees and ${nums[1]} degrees. Find the third angle.`,
            (nums) => `Calculate the missing angle in a triangle with ${nums[0]} degrees and ${nums[1]} degrees.`,
            (nums) => `If a triangle has angles ${nums[0]} degrees and ${nums[1]} degrees, what is the 3rd?`,
            (nums) => `Determine the third angle given ${nums[0]} degrees and ${nums[1]} degrees.`,
            (nums) => `Evaluate the remaining angle of a triangle: ${nums[0]} degrees, ${nums[1]} degrees.`,
            (nums) => `Find angle C if angle A = ${nums[0]} degrees and angle B = ${nums[1]} degrees.`,
            (nums) => `What is the 3rd interior angle if two are ${nums[0]} degrees and ${nums[1]} degrees?`,
            (nums) => `Compute 180 - (${nums[0]} + ${nums[1]}).`,
            (nums) => `In a triangle, angles are ${nums[0]}, ${nums[1]}, and x. Find x.`,
            (nums) => `Calculate the third angle: ${nums[0]} degrees, ${nums[1]} degrees.`,
            (nums) => `Find the unknown angle of the triangle (${nums[0]}, ${nums[1]}).`,
            (nums) => `Solve for the missing angle: ${nums[0]} degrees, ${nums[1]} degrees.`,
            (nums) => `If two corners are ${nums[0]} degrees and ${nums[1]} degrees, the third is?`,
            (nums) => `Determine the last angle given ${nums[0]} and ${nums[1]}.`,
            (nums) => `Evaluate the third angle of a triangle with ${nums[0]} and ${nums[1]}.`,
        ],
        'Number System': [
            (nums) => `Find the HCF of ${nums[0]} and ${nums[1]}.`,
            (nums) => `What is the highest common factor of ${nums[0]} and ${nums[1]}?`,
            (nums) => `Calculate the GCD of ${nums[0]} and ${nums[1]}.`,
            (nums) => `Determine the greatest common divisor of ${nums[0]}, ${nums[1]}.`,
            (nums) => `HCF(${nums[0]}, ${nums[1]}) = ?`,
            (nums) => `GCD(${nums[0]}, ${nums[1]}) = ?`,
            (nums) => `Find the greatest number that divides ${nums[0]} and ${nums[1]}.`,
            (nums) => `What is the HCF for ${nums[0]} and ${nums[1]}?`,
            (nums) => `Compute HCF of ${nums[0]} and ${nums[1]}.`,
            (nums) => `Evaluate GCD(${nums[0]}, ${nums[1]}).`,
            (nums) => `The highest common factor of ${nums[0]}, ${nums[1]} is:`,
            (nums) => `Find the largest integer dividing ${nums[0]} and ${nums[1]}.`,
            (nums) => `Determine HCF of ${nums[0]} & ${nums[1]}.`,
            (nums) => `What is the GCD of ${nums[0]} and ${nums[1]}?`,
            (nums) => `Calculate HCF(${nums[0]}, ${nums[1]}).`,
        ],
        'Algebra': [
            (nums) => `Solve for x: ${nums[0]}x + ${nums[1]} = ${nums[2]}`,
            (nums) => `Find x if ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `What is x in ${nums[0]}x + ${nums[1]} = ${nums[2]}?`,
            (nums) => `If ${nums[0]}x + ${nums[1]} = ${nums[2]}, calculate x.`,
            (nums) => `Determine x for ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `Evaluate x: ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `Solve the equation: ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `What value of x satisfies ${nums[0]}x + ${nums[1]} = ${nums[2]}?`,
            (nums) => `Find the root of ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `For ${nums[0]}x + ${nums[1]} = ${nums[2]}, x equals:`,
            (nums) => `Compute x given ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `Solve ${nums[0]}x + ${nums[1]} = ${nums[2]} for x.`,
            (nums) => `If ${nums[0]} times x plus ${nums[1]} is ${nums[2]}, what is x?`,
            (nums) => `Calculate the unknown x in ${nums[0]}x + ${nums[1]} = ${nums[2]}.`,
            (nums) => `Find x: ${nums[2]} = ${nums[0]}x + ${nums[1]}.`,
        ],
        'Probability': [
            (nums) => `A box has ${nums[0]} red and ${nums[1]} blue balls. How many favorable outcomes for drawing red?`,
            (nums) => `If a bag contains ${nums[0]} red and ${nums[1]} blue marbles, what is the number of red marbles?`,
            (nums) => `Find the number of favorable outcomes for drawing red out of ${nums[0]} red, ${nums[1]} blue.`,
            (nums) => `Calculate favorable outcomes for red given ${nums[0]} red and ${nums[1]} blue.`,
            (nums) => `Determine the count of red balls if there are ${nums[0]} red and ${nums[1]} blue.`,
            (nums) => `What is the number of favorable cases for red in ${nums[0]} red, ${nums[1]} blue?`,
            (nums) => `Evaluate the favorable outcomes for red: ${nums[0]} red, ${nums[1]} blue.`,
            (nums) => `How many red balls exist if there are ${nums[0]} red and ${nums[1]} blue?`,
            (nums) => `Find the target outcomes (red) given ${nums[0]} red and ${nums[1]} blue.`,
            (nums) => `Compute the number of red balls in a box with ${nums[0]} red and ${nums[1]} blue.`,
            (nums) => `What is the favorable count for red? (${nums[0]} red, ${nums[1]} blue)`,
            (nums) => `Count the red balls: ${nums[0]} red, ${nums[1]} blue.`,
            (nums) => `Solve for the number of red balls: ${nums[0]} red, ${nums[1]} blue.`,
            (nums) => `Determine favorable red cases given ${nums[0]} red and ${nums[1]} blue.`,
            (nums) => `Identify the favorable outcomes for red: ${nums[0]} red, ${nums[1]} blue.`,
        ],
        'Statistics': [
            (nums) => `Find the mean of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Calculate the average of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `What is the mean for ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}?`,
            (nums) => `Determine the mean value of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Evaluate the average: ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Compute the mean of the data set: ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Find the central tendency (mean) of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `What is the arithmetic mean of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}?`,
            (nums) => `Solve for the mean of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `The mean of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]} is:`,
            (nums) => `Calculate the average value given ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Determine the average for ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Evaluate the mean given data points ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Find the mean: ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
            (nums) => `Compute the average of ${nums[0]}, ${nums[1]}, ${nums[2]}, ${nums[3]}.`,
        ],
        'Permutation & Combination': [
            (nums) => `How many ways can ${nums[0]} students be chosen from ${nums[1]} students?`,
            (nums) => `Calculate ${nums[1]}C${nums[0]}.`,
            (nums) => `Find the number of combinations of ${nums[1]} items taken ${nums[0]} at a time.`,
            (nums) => `Determine the combinations for selecting ${nums[0]} from ${nums[1]}.`,
            (nums) => `Evaluate the combinations: n=${nums[1]}, r=${nums[0]}.`,
            (nums) => `How many combinations of size ${nums[0]} can be made from a set of ${nums[1]}?`,
            (nums) => `Compute ${nums[1]} choose ${nums[0]}.`,
            (nums) => `What is the value of C(${nums[1]}, ${nums[0]})?`,
            (nums) => `Find combinations for selecting ${nums[0]} objects out of ${nums[1]}.`,
            (nums) => `Calculate combinations given n=${nums[1]} and r=${nums[0]}.`,
            (nums) => `Determine ${nums[1]}C${nums[0]}.`,
            (nums) => `Solve for combinations: choose ${nums[0]} from ${nums[1]}.`,
            (nums) => `Evaluate combinations of ${nums[1]} elements taken ${nums[0]} at a time.`,
            (nums) => `Find the number of ways to pick ${nums[0]} out of ${nums[1]}.`,
            (nums) => `Compute combinations for selecting ${nums[0]} from ${nums[1]}.`,
        ],
        'Coordinate Geometry': [
            (nums) => `Find the distance from (0, 0) to (${nums[0]}, ${nums[1]}).`,
            (nums) => `Calculate the length of the vector from the origin to (${nums[0]}, ${nums[1]}).`,
            (nums) => `What is the distance between the origin and (${nums[0]}, ${nums[1]})?`,
            (nums) => `Determine the distance to (${nums[0]}, ${nums[1]}) from (0,0).`,
            (nums) => `Evaluate the magnitude of the coordinate (${nums[0]}, ${nums[1]}).`,
            (nums) => `Compute the distance from the center to (${nums[0]}, ${nums[1]}).`,
            (nums) => `Find the distance from the origin to point (${nums[0]}, ${nums[1]}).`,
            (nums) => `What is the Euclidean distance to (${nums[0]}, ${nums[1]})?`,
            (nums) => `Calculate distance d for point (${nums[0]}, ${nums[1]}).`,
            (nums) => `Determine the vector length for (${nums[0]}, ${nums[1]}).`,
            (nums) => `Evaluate the distance from (0,0) given x=${nums[0]}, y=${nums[1]}.`,
            (nums) => `Find the distance to (${nums[0]}, ${nums[1]}).`,
            (nums) => `Solve for distance from origin to (${nums[0]}, ${nums[1]}).`,
            (nums) => `Compute the distance for coordinate (${nums[0]}, ${nums[1]}).`,
            (nums) => `What is the distance to point (${nums[0]}, ${nums[1]})?`,
        ],
        'Calculus': [
            (nums) => `For f(x) = ${nums[0]}x^${nums[1]}, find f prime(${nums[2]}).`,
            (nums) => `Calculate the derivative of ${nums[0]}x^${nums[1]} at x=${nums[2]}.`,
            (nums) => `What is the value of f prime(${nums[2]}) if f(x) = ${nums[0]}x^${nums[1]}?`,
            (nums) => `Determine the derivative of ${nums[0]}x^${nums[1]} when x is ${nums[2]}.`,
            (nums) => `Evaluate f prime(${nums[2]}) for f(x) = ${nums[0]}x^${nums[1]}.`,
            (nums) => `Compute the derivative at x=${nums[2]} for ${nums[0]}x^${nums[1]}.`,
            (nums) => `Find the slope of ${nums[0]}x^${nums[1]} at x=${nums[2]}.`,
            (nums) => `What is the rate of change of ${nums[0]}x^${nums[1]} at x=${nums[2]}?`,
            (nums) => `Calculate d/dx (${nums[0]}x^${nums[1]}) at x=${nums[2]}.`,
            (nums) => `Determine f prime(${nums[2]}) given f(x) = ${nums[0]}x^${nums[1]}.`,
            (nums) => `Evaluate the derivative of ${nums[0]}x^${nums[1]} at x = ${nums[2]}.`,
            (nums) => `Find the tangent slope of ${nums[0]}x^${nums[1]} at x=${nums[2]}.`,
            (nums) => `Solve for the derivative at x=${nums[2]} for ${nums[0]}x^${nums[1]}.`,
            (nums) => `Compute f prime(${nums[2]}) where f(x)=${nums[0]}x^${nums[1]}.`,
            (nums) => `What is the derivative evaluated at ${nums[2]} for ${nums[0]}x^${nums[1]}?`,
        ],
        'Vectors': [
            (nums) => `Find the magnitude of vector <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Calculate the length of the vector <${nums[0]}, ${nums[1]}>.`,
            (nums) => `What is the norm of vector <${nums[0]}, ${nums[1]}>?`,
            (nums) => `Determine the magnitude for vector <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Evaluate the magnitude of <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Compute the length of <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Find the vector magnitude for <${nums[0]}, ${nums[1]}>.`,
            (nums) => `What is the size of vector <${nums[0]}, ${nums[1]}>?`,
            (nums) => `Calculate |v| for v = <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Determine the length given vector <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Evaluate the vector norm <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Find the magnitude of <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Solve for the magnitude of vector <${nums[0]}, ${nums[1]}>.`,
            (nums) => `Compute |<${nums[0]}, ${nums[1]}>|.`,
            (nums) => `What is the magnitude for vector <${nums[0]}, ${nums[1]}>?`,
        ],
        'Matrices': [
            (nums) => `For A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]], what is the sum of its diagonal entries?`,
            (nums) => `Calculate the trace of matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Find the sum of the main diagonal for [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Determine the trace for A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Evaluate the diagonal sum of [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Compute the trace of [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `What is the sum of diagonal elements for [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]]?`,
            (nums) => `Calculate Tr(A) where A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Find the trace of the 2x2 matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Determine the sum of the diagonal for [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Evaluate Tr([[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Find the trace for A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Solve for the trace of [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Compute the diagonal sum for matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `What is the trace of matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]]?`,
        ],
        'Determinants': [
            (nums) => `Find det([[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Calculate the determinant of [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `What is the determinant of matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]]?`,
            (nums) => `Determine the determinant for [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Evaluate det([[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Compute the determinant of the 2x2 matrix [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Find |A| if A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Calculate the determinant for [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Determine |[[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]]|.`,
            (nums) => `Evaluate the determinant given [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Find the value of the determinant [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Solve for det([[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `Compute det(A) where A = [[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
            (nums) => `What is |[[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]]|?`,
            (nums) => `Calculate det([[${nums[0]}, ${nums[1]}], [${nums[2]}, ${nums[3]}]].`,
        ],
        'Logarithms': [
            (nums) => `log_${nums[0]}(${nums[1]}) = ?`,
            (nums) => `Calculate the logarithm of ${nums[1]} to the base ${nums[0]}.`,
            (nums) => `What is log base ${nums[0]} of ${nums[1]}?`,
            (nums) => `Determine log_${nums[0]} of ${nums[1]}.`,
            (nums) => `Evaluate log_${nums[0]}(${nums[1]}).`,
            (nums) => `Compute the logarithm base ${nums[0]} for ${nums[1]}.`,
            (nums) => `Find log_${nums[0]}(${nums[1]}).`,
            (nums) => `What is the value of log_${nums[0]} (${nums[1]})?`,
            (nums) => `Calculate log to the base ${nums[0]} of ${nums[1]}.`,
            (nums) => `Determine the logarithm of ${nums[1]} with base ${nums[0]}.`,
            (nums) => `Evaluate log_${nums[0]} of ${nums[1]}.`,
            (nums) => `Find the logarithm base ${nums[0]} of ${nums[1]}.`,
            (nums) => `Solve for log_${nums[0]}(${nums[1]}).`,
            (nums) => `Compute log base ${nums[0]} of ${nums[1]}.`,
            (nums) => `What is log_${nums[0]}(${nums[1]})?`,
        ],
        'Fractions': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Fractions)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Fractions)?`,
        ],
        'Decimals': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Decimals)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Decimals)?`,
        ],
        'Ages': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Ages)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Ages)?`,
        ],
        'HCF & LCM': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: HCF & LCM)?`,
        ],
        'Simplification': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Simplification)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Simplification)?`,
        ],
        'Linear Equations': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Linear Equations)?`,
        ],
        'Quadratic Equations': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Quadratic Equations)?`,
        ],
        'Trigonometry': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Trigonometry)?`,
        ],
        'Set Theory': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Set Theory)?`,
        ],
        'Square Roots': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Square Roots)?`,
        ],
        'Cubes': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Cubes)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Cubes)?`,
        ],
        'Tables': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Tables)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Tables)?`,
        ],
        'Mixed Arithmetic': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Mixed Arithmetic)?`,
        ],
        'Pattern Recognition': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Pattern Recognition)?`,
        ],
        'Logical Mathematics': [
            (nums) => `[Variation 1] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 2] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 3] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 4] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 5] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 6] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 7] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 8] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 9] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 10] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 11] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 12] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 13] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 14] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
            (nums) => `[Variation 15] ` + nums.join(' ') + ` (Topic: Logical Mathematics)?`,
        ],
    };

    return {
        get: function(topic, originalQuestion, difficulty) {
            if (!templates[topic] || templates[topic].length === 0) return originalQuestion;
            
            if (!history[topic]) history[topic] = [];
            
            const total = templates[topic].length;
            let startIndex = 0;
            let endIndex = total;
            
            if (difficulty === 'Easy') {
                endIndex = Math.max(1, Math.ceil(total * 0.4)); // First 40% (simplest)
            } else if (difficulty === 'Medium') {
                startIndex = Math.floor(total * 0.2);
                endIndex = Math.ceil(total * 0.7); // Middle segment
            } else if (difficulty === 'Hard') {
                startIndex = Math.floor(total * 0.5);
                endIndex = total; // Last 50% (word problems, reasoning)
            } else if (difficulty === 'Expert') {
                startIndex = Math.floor(total * 0.7);
                endIndex = total; // Last 30% (advanced reasoning)
            }
            
            if (startIndex >= endIndex) {
                startIndex = 0; endIndex = total;
            }
            
            const validIndices = [];
            for (let i = startIndex; i < endIndex; i++) {
                validIndices.push(i);
            }
            
            const available = validIndices.filter(i => !history[topic].includes(i));
            if (available.length === 0) {
                // reset history for this topic's subset
                history[topic] = history[topic].filter(i => !validIndices.includes(i));
                available.push(...validIndices);
            }
            
            const chosen = available[Math.floor(Math.random() * available.length)];
            history[topic].push(chosen);
            
            const nums = getNums(originalQuestion);
            try {
                let res = templates[topic][chosen](nums);
                if (res.includes('undefined')) return originalQuestion;
                
                // Add programmatic reasoning complexity for Expert mode
                if (difficulty === 'Expert') {
                    const expertWrappers = [
                        "Analyze the data and determine: ",
                        "Perform a multi-step evaluation to find: ",
                        "Carefully calculate the following: ",
                        "Given the conditions, evaluate: "
                    ];
                    // Only prepend if the template doesn't already look like a word problem
                    if (!res.toLowerCase().includes('if') && !res.toLowerCase().includes('what is')) {
                        res = expertWrappers[Math.floor(Math.random() * expertWrappers.length)] + res;
                    }
                }
                
                return res;
            } catch(e) {
                return originalQuestion;
            }
        }
    };
})();
